
set(SRC_FILES
    src/main.c
    src/App.c
    src/App.h
    src/base/Window.c
    src/base/Window.h
    src/base/Graphics.c
    src/base/Graphics.h
    src/base/Texture.c
    src/base/Texture.h
    src/base/Button.c
    src/base/Button.h
    src/base/Rectangle.c
    src/base/Rectangle.h
    src/base/Box.h
    src/base/Box.c
    src/base/SceneManager.h
    src/base/SceneManager.c
    src/base/DataZipFile.h
    src/base/DataZipFile.c
    src/base/LinkedList.h
    src/base/LinkedList.c
    src/base/rect.h
    src/base/TextureFilter.h
    src/base/private/Timer.h
    src/base/private/Timer.c
    src/base/opengl_renderer/GL.h
    src/base/opengl_renderer/GLProgram.h
    src/base/opengl_renderer/GLProgram.c
    src/base/opengl_renderer/OpenGLRenderer.c
    src/base/opengl_renderer/OpenGLRenderer.h
    src/base/opengl_renderer/GLBuffer.h
    src/base/opengl_renderer/GLBuffer.c
    src/base/opengl_renderer/GLTexture.h
    src/base/opengl_renderer/GLTexture.c
    src/scene_game/SceneGameRect.h
    src/scene_game/SceneGame.c
    src/scene_game/SceneGame.h
    src/scene_game/board/GameBoard.c
    src/scene_game/board/GameBoard.h
    src/scene_game/board/board_util.c
    src/scene_game/board/board_util.h
    src/scene_game/Sidebar.c
    src/scene_game/Sidebar.h
    src/scene_game/Footer.c
    src/scene_game/Footer.h
    src/scene_game/Header.c
    src/scene_game/Header.h)
